project/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='dashboard', permanent=False)),
    path('accounts/login/',
        auth_views.LoginView.as_view(template_name='accounts/login.html', 
            redirect_authenticated_user=True),
        name="login"),
    path('accounts/logout/',
        auth_views.LogoutView.as_view(),
        name="logout"),
    # path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'), name='password_reset'),
    # path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),

    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('sse/dasboard/', views.sse_dashboard, name="sse_dashboard"),
    path("dashboard/int_graph/", views.get_int_graph, name="int_graph"),
    
    path('users/', views.UserManagementView.as_view(), name="users"),
    path('edit_user/<int:pk>/', views.EditUserView.as_view(), name="edit_user"),
    path('drop_user/<int:pk>/', views.DropUser, name="drop_user"),
]

project/base/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("service/", views.ServiceView.as_view(), name="service"),
    path("delete_service/<int:pk>/", views.DeleteService, name="delete_service"),
    path("edit_service/<int:pk>/", views.EditServiceView.as_view(), name="edit_service"),
    path("project/", views.ProjectView.as_view(), name="project"),
    path("delete_project/<int:pk>/", views.DeleteProject, name="delete_project"),
    path("edit_project/<int:pk>/", views.EditProjectView.as_view(), name="edit_project"),

    path("enquiry/", views.EnquiryView.as_view(), name="enquiry"),
    path('load_districts/', views.load_districts, name="load_districts"),
    path('follow_up/', views.FollowUpView.as_view(), name="follow_up"),
    path("view_enquiry/<int:pk>/", views.ViewEnquiry, name="view_enquiry"),
    path("edit_enquiry/<int:pk>/", views.EditEnquiryView.as_view(), name="edit_enquiry"),
    path("drop_enquiry/<int:pk>/", views.DropEnquiry, name="drop_enquiry"),
    path("add_follow_up/<int:pk>/", views.AddFollowUpView.as_view(), name="add_follow_up"),

    path('work_list/', views.WorkListView.as_view(), name="work_list"),
    path("view_work/<int:pk>/", views.ViewWork, name="view_work"),
    path("edit_work/<int:pk>/", views.EditWorkView.as_view(), name="edit_work"),
    path("assign_work/<int:pk>/", views.AssignWorkView.as_view(), name="assign_work"),
    path("add_payment/<int:pk>/", views.AddPaymentView.as_view(), name="add_payment"),
    path("update_status/<int:pk>/", views.UpdateWorkStatusView.as_view(), name="update_status"),
    path("add_payment_remark/<int:pk>/", views.AddPaymentRemarkView.as_view(), name="add_payment_remark"),
    path("drop_work/<int:pk>/", views.DropWork, name="drop_work"),

    path('completed_work_list/', views.CompletedWorkListView.as_view(), name="completed_work_list"),
    path("view_completed_work/<int:pk>/", views.ViewCompletedWork, name="view_completed_work"),
    path("work_payment/<int:pk>/", views.WorkPaymentView.as_view(), name="work_payment"),
    
    path('dropped_list/', views.DroppedListView.as_view(), name="dropped_list"),
    path("view_dropped/<int:pk>/", views.ViewDropped, name="view_dropped"),

    path('payments/', views.PaymentsView.as_view(), name="payments"),
    path('payment_due_list/', views.PaymentDueListView.as_view(), name="payment_due_list"),
    path('site_eng_status/', views.SiteEngStatusListView.as_view(), name="site_eng_status"),
    path('site_eng_status/<int:pk>/', views.SiteEngStatusView.as_view(), name="site_eng_status_view"),
]

project/project/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('base.urls')),
    path("", include("accounts.urls")),
] 

project/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    ROLE_CHOICES = [
        ('admin', 'Admin'),
        ('manager', 'Manager'),
        ('engineer', 'Site Engineer'),
        ('assistant', 'Office Assistant'),
    ]

    role = models.CharField(choices=ROLE_CHOICES, max_length=100)
    email = models.EmailField(unique=True, blank=False)

    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

project/accounts/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'role']

project/accounts/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.http import HttpResponse, JsonResponse, StreamingHttpResponse
from django.views import View

from accounts.mixins import RoleRequiredMixin
from accounts.decorators import role_required

from .models import User
from django.db.models import Max, Count, Sum
from django.db.models.functions import TruncMonth
from base.models import Customer, Enquiry, Work, Payment
from .forms import UserForm

from django.core.mail import EmailMultiAlternatives
import threading
from django.contrib.auth.tokens import default_token_generator
from django.urls import reverse
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes

from datetime import datetime
from dateutil.relativedelta import relativedelta
import time
import json
import redis


def get_dashboard_data():
    # Getting all the card data
    no_of_customers=Customer.objects.all().count()
    no_of_closed_enq = Enquiry.objects.exclude(status="enquired").count()
    no_of_unclosed_enq = Enquiry.objects.filter(status="enquired").count()
    no_of_cmp_work = Work.objects.filter(status="completed").count()
    no_of_ong_work = Work.objects.filter(status__in=["assigned", "in-progress"]).count()
    no_of_upc_work = Work.objects.filter(status="pending").count()
    card_data={'no_of_customers': no_of_customers, 'no_of_closed_enq': no_of_closed_enq, 'no_of_unclosed_enq': 
        no_of_unclosed_enq, 'no_of_cmp_work': no_of_cmp_work, 'no_of_ong_work': no_of_ong_work, 'no_of_upc_work':
        no_of_upc_work
    }



    # Getting data from monthly enquiry area graph
    end = datetime.now()
    start = (end - relativedelta(months=6)).replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    months = [] # List having all the past 6 months
    temp = start
    while temp <= end:
        months.append(temp.strftime("%B %y"))
        if temp.month == 12:
            temp = temp.replace(year=temp.year + 1, month=1)
        else:
            temp = temp.replace(month=temp.month + 1)
        
    enquiry_qs = (
        Enquiry.objects
        .filter(created_at__gte=start, created_at__lte=end)
        .annotate(month=TruncMonth('created_at'))
        .values('month')
        .annotate(count=Count('id'))
    ) 

    enquiry_counts = {
        entry['month'].strftime("%B %y"): entry['count']
        for entry in enquiry_qs
    }# Dictionary showing respective months and their enquiry counts

    # Prepare final data list with 0 for months with no data
    no_of_enquiries = [enquiry_counts.get(month, 0) for month in months]
    graph_1 = {'months': months, 'no_of_enquiries': no_of_enquiries}



    # Site Engineer Table
    site_engineers = User.objects.filter(role="engineer")
    site_engineers = [
        {
            "id": obj.id,
            "name": f"{obj.first_name} {obj.last_name}"
        }
        for obj in site_engineers
    ]


    # Doughnut Graph for no of projects
    no_of_pvt_work = Work.objects.filter(project_type__project_type="Private Project").count()
    no_of_gov_work = Work.objects.filter(project_type__project_type="Government Project").count()
    no_of_tot_work = no_of_gov_work+no_of_pvt_work
    graph_2 = {'no_of_tot_work':no_of_tot_work, 'no_of_pvt_work': no_of_pvt_work, 'no_of_gov_work': no_of_gov_work}


    # Payment Due List Table
    payment_due_list = Work.objects.all()
    payment_due_list = [
        {
            "id": obj.id,
            "customer": obj.customer.__str__(),  
            "estimate_amount": float(obj.estimate_amount),      
            "amount_left": float(obj.get_amount_left()),
        }
        for obj in payment_due_list if not obj.is_paid
    ]


    # Payment Mode Graph
    pay_choices = Payment.PAYMENT_CHOICES
    payment_modes = [choice[1] for choice in pay_choices]
    payments = Payment.objects.values('mode').annotate(count=Sum('amount'))
    mode_label_map = dict(pay_choices)
    payments = [
        {'mode': mode_label_map.get(row['mode'], row['mode']), 'count': row['count']}
        for row in payments
    ]
    no_of_payments = {
        payment['mode']: float(payment['count'])
        for payment in payments
    }
    no_of_payments = [no_of_payments.get(mode, 0) for mode in payment_modes]
    graph_3={"payment_modes": payment_modes, 'no_of_payments': no_of_payments}


    context={'card_data': card_data, 'graph_1': graph_1, 'site_engineers': site_engineers, 
            'graph_2': graph_2, 'payment_due_list': payment_due_list, 'graph_3': graph_3}
    
    return context


def get_dashboard_data_eng(eng):
    # Getting all the card data
    no_of_cmp_work = Work.objects.filter(status="completed", site_engineer=eng).count()
    no_of_ong_work = Work.objects.filter(status__in=["assigned", "in-progress"], site_engineer=eng).count()
    card_data={'no_of_cmp_work': no_of_cmp_work, 'no_of_ong_work': no_of_ong_work}


    # Getting data from monthly work area graph
    end = datetime.now()
    start = (end - relativedelta(months=6)).replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    months = [] # List having all the past 6 months
    temp = start
    while temp <= end:
        months.append(temp.strftime("%B %y"))
        if temp.month == 12:
            temp = temp.replace(year=temp.year + 1, month=1)
        else:
            temp = temp.replace(month=temp.month + 1)
        
    work_qs = (
        Work.objects
        .filter(created_at__gte=start, created_at__lte=end, site_engineer=eng)
        .annotate(month=TruncMonth('created_at'))
        .values('month')
        .annotate(count=Count('id'))
    ) 

    work_counts = {
        entry['month'].strftime("%B %y"): entry['count']
        for entry in work_qs
    }# Dictionary showing respective months and their work counts

    # Prepare final data list with 0 for months with no data
    no_of_works = [work_counts.get(month, 0) for month in months]
    graph_1 = {'months': months, 'no_of_works': no_of_works}



    # Work Status Bar Grpah
    work_status=["Assigned", "In Progress", "Completed"]
    work_choices = Work._meta.get_field('status').choices
    works = Work.objects.filter(site_engineer=eng).values('status').annotate(count=Count('id'))
    status_label_map = dict(work_choices)
    works = [
        {'status': status_label_map.get(row['status'], row['status']), 'count': row['count']}
        for row in works
    ]
    no_of_work_stats = {
        work['status']: int(work['count'])
        for work in works
    }
    no_of_work_stats = [no_of_work_stats.get(mode, 0) for mode in work_status]
    graph_2={"work_status": work_status, 'no_of_work_stats': no_of_work_stats}


    context={'card_data': card_data, 'graph_1': graph_1, 'graph_2': graph_2}
    return context




def get_int_graph(request):
    label_to_code = {label: code for code, label in Payment.PAYMENT_CHOICES}
    mode=request.GET.get("mode")
    mode = label_to_code.get(mode)

    end = datetime.now()
    start = (end - relativedelta(months=6)).replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    months = [] # List having all the past 6 months
    temp = start
    while temp <= end:
        months.append(temp.strftime("%B %y"))
        if temp.month == 12:
            temp = temp.replace(year=temp.year + 1, month=1)
        else:
            temp = temp.replace(month=temp.month + 1)


    payment_qs = (
        Payment.objects
        .filter(payment_at__gte=start, payment_at__lte=end, mode=mode)
        .annotate(month=TruncMonth('payment_at'))
        .values('month')
        .annotate(count=Sum('amount'))
    ) 

    payment_counts = {
        entry['month'].strftime("%B %y"): entry['count']
        for entry in payment_qs
    }# Dictionary showing respective months and their enquiry counts

    # Prepare final data list with 0 for months with no data
    no_of_payments = [payment_counts.get(month, 0) for month in months]
    graph = {'labels': months, 'data': no_of_payments}
    return JsonResponse(graph)



def event_stream(request):
    r = redis.Redis(host="redis", port=6379, db=0, decode_responses=True)
    pubsub = r.pubsub()
    pubsub.subscribe("dashboard_updates")

    try:
        for message in pubsub.listen():
            if message['type'] == 'message':
                if request.user.role == "engineer":
                    data=get_dashboard_data_eng(request.user)
                else:
                    data = get_dashboard_data()
                yield f"event: update\ndata: {json.dumps(data)}\n\n"
                time.sleep(0.5)
    except GeneratorExit:
        print("Client disconnected from SSE.")
    finally:
        pubsub.unsubscribe("dashboard_updates")
        pubsub.close()


def sse_dashboard(request):
    response = StreamingHttpResponse(event_stream(request), content_type='text/event-stream')
    response['Cache-Control'] = 'no-cache'
    return response




class EmailThread(threading.Thread):
    def __init__(self, email):
        self.email = email
        threading.Thread.__init__(self)

    def run(self):
        self.email.send()


def send_password_reset_email(user, request):
    uid = urlsafe_base64_encode(force_bytes(user.pk))
    token = default_token_generator.make_token(user)
    reset_url = request.build_absolute_uri(
        reverse('password_reset_confirm', kwargs={'uidb64': uid, 'token': token})
    )

    subject = "Set your password"
    from_email = 'admin@example.com'
    to_email = [user.email]

    html_content = render_to_string('accounts/password_reset_email.html', {
        'user': user,
        'reset_url': reset_url,
    })
    text_content = f"Hello {user.first_name},\nUse this link to set your password: {reset_url}"

    email = EmailMultiAlternatives(subject, text_content, from_email, to_email)
    email.attach_alternative(html_content, "text/html")
    EmailThread(email).start()


class DashboardView(RoleRequiredMixin, View):
    template1="accounts/dashboard.html"

project/accounts/templates/accounts/dashboard_eng.html
{% extends 'accounts/main.html' %} 

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="container my-4">
    <div class="row mb-3">
        <div class="col-md-6">
            <div class="card dashboard-card">
                <div class="card-body" style="height: 9rem;">
                    <h5 class="card-title text-center">Completed Work</h5>
                    <h1 class="card-text text-center" id="no_of_cmp_works">{{ card_data.no_of_cmp_work }}</h1>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card dashboard-card">
                <div class="card-body" style="height: 9rem;">
                    <h5 class="card-title text-center">Ongoing Work</h5>
                    <h1 class="card-text text-center" id="no_of_ong_works">{{ card_data.no_of_ong_work }}</h1>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-3">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body" style="height: 23rem;">
                    <h4 class="card-title text-center mb-4">Monthly Work Status</h4>
                    <canvas id="monthlyWorks"></canvas>
                </div>
            </div>            
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body" style="height: 23rem;">
                    <h4 class="card-title text-center mb-4">Work Status</h4>
                    <canvas id="workStatus"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<!-- Chart.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js" integrity="sha512-ZwR1/gSZM3ai6vCdI+LVF1zSq/5HznD3ZSTk7kajkaj4D292NLuduDCO1c/NT8Id+jE58KYLKT7hXnbtryGmMg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
    const months_labels = {{ graph_1.months|safe }};
    const works_data = {{ graph_1.no_of_works|safe }};

    // Line Chart 
    const ctx1 = document.getElementById("monthlyWorks").getContext("2d");
    window.chart1 = new Chart(ctx1, {
        type: 'line',
        data: {
            labels: months_labels,
            datasets: [{
                label: 'Works',
                data: works_data,
                fill: true,
                tension: 0.5,
            }]
        },
        options: {
            scales: {
                x: { title: { text: "Month", display: true } },
                y: { beginAtZero: true, title: { text: "Works", display: true } }
            }
        }
    });



    const status = {{ graph_2.work_status|safe }};
    const no_of_work_stats = {{ graph_2.no_of_work_stats|safe }};
    const ctx2 = document.getElementById("workStatus").getContext("2d");
    window.chart2 = new Chart(ctx2, {
        type: 'bar',
        data: {
            labels: status,
            datasets: [{
                label: 'Work',
                data: no_of_work_stats,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    ],
                    borderColor: [
                    'rgb(255, 99, 132)',
                    'rgb(255, 159, 64)',
                    'rgb(75, 192, 192)',
                    ],
                    borderWidth: 1,

            }],
        },
        options: {
            scales: {
                x: { title: { text: "Status", display: true } },
                y: { beginAtZero: true, title: { text: "Work", display: true } }
            },
        }
    });



    function connectSSE() {
        // Server-Sent Events Setup
        const evtSource = new EventSource("/sse/dasboard/");
        evtSource.addEventListener("update", function (event) {
            const data = JSON.parse(event.data);
            console.log(data);

            // 🔄 Update card values
            document.getElementById("no_of_cmp_works").innerText = data.card_data.no_of_cmp_work;
            document.getElementById("no_of_ong_works").innerText = data.card_data.no_of_ong_work;

            // 🔄 Update Line Chart (Monthly Works)
            if (window.chart1) {
                window.chart1.data.labels = data.graph_1.months;
                window.chart1.data.datasets[0].data = data.graph_1.no_of_works;
                window.chart1.update();
            }
            // Update Bar Chart(Work Status)
            if (window.chart2) {
                window.chart2.data.labels = data.graph_2.work_status;
                window.chart2.data.datasets[0].data = data.graph_2.no_of_work_stats;
                window.chart2.update();
            }

        });

        evtSource.onerror = function (err) {
            console.error("SSE connection error. Attempting to reconnect...", err);
            console.log("Error");
            source.close();
            setTimeout(connectSSE, 5000);
        };
    }

    document.addEventListener("DOMContentLoaded", connectSSE);
</script>
{% endblock scripts %}

project/accounts/templates/accounts/edit_user.html
{% load widget_tweaks %}
<form action="{% url 'edit_user' form.instance.id %}" method="POST" id='editUserForm'>
    {% csrf_token %}
	<div class="modal-header">
		<h5 class="modal-title" id="editModalLabel">Edit User</h5>
		<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
	</div>
	<div class="modal-body">
		<div class="row justify-content-center mb-4">
            <div class="col-12">
                {% csrf_token %}

                <div class="row mb-4">
                <div class="col-md-6">
                    <div class="form-floating">
                    {% render_field form.first_name class="form-control" placeholder="First Name" %}
                    <label for="{{ form.first_name.id_for_label }}">First Name</label>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-floating">
                    {% render_field form.last_name class="form-control" placeholder="Last Name" %}
                    <label for="{{ form.last_name.id_for_label }}">Last Name</label>
                    </div>
                </div>
                </div>

                <div class="row mb-4">
                <div class="col-md-6">
                    <div class="form-floating">
                    {% render_field form.username class="form-control" placeholder="Username" %}
                    <label for="{{ form.username.id_for_label }}">Username</label>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-floating">
                    {% render_field form.email class="form-control" placeholder="Email" %}
                    <label for="{{ form.email.id_for_label }}">Email</label>
                    </div>
                </div>
                </div>

                <div class="row mb-4">
                <div class="col-md-6">
                    <div class="form-floating">
                    {% render_field form.role class="form-select" %}
                    <label for="{{ form.role.id_for_label }}">Role</label>
                    </div>
                </div>
                </div>
            </div>
        </div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
		<button type="submit" class="btn btn-primary" id="edit-user-btn">Save Changes</button>
	</div>
</form>

<script>
	$("#editModalUser").modal('show');
</script>

project/accounts/templates/accounts/navheader.html
{% load static %}
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <button class="toggle-btn navbar-toggler" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="d-flex align-items-center gap-3">
      <div class="d-flex align-items-center">
        <img src="{% static 'base/images/user.png' %}" alt="User" width="35" height="35" class="rounded-circle me-2" />
        <div class="d-none d-sm-block text-center">
          <div class="fw-semibold">{{ request.user.first_name }} {{ request.user.last_name }}</div>
          <small class="text-muted">{{ request.user.get_role_display }}</small>
        </div>
      </div>
      <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit" class="fas fa-sign-out-alt me-1 btn btn-outline-danger btn-sm ms-3">Logout</button>
      </form>
    </div>
  </div>
</nav>

project/accounts/templates/accounts/user_management.html
{% extends 'accounts/main.html' %}
{% load widget_tweaks %}

{% block title %}User Management{% endblock %}

{% block content %}
{% if form_errors %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <ul>
    {% for error in form_errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endif %}

<div class="container my-4">
  <h3 class="mb-4">Add User</h3>
  <form method="POST">
    <div class="row justify-content-center mb-4">
        <div class="col-12">
            {% csrf_token %}

            <div class="row mb-4">
            <div class="col-md-6">
                <div class="form-floating">
                {% render_field form.first_name class="form-control" placeholder="First Name" %}
                <label for="{{ form.first_name.id_for_label }}">First Name</label>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-floating">
                {% render_field form.last_name class="form-control" placeholder="Last Name" %}
                <label for="{{ form.last_name.id_for_label }}">Last Name</label>
                </div>
            </div>
            </div>

            <div class="row mb-4">
            <div class="col-md-6">
                <div class="form-floating">
                {% render_field form.username class="form-control" placeholder="Username" %}
                <label for="{{ form.username.id_for_label }}">Username</label>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-floating">
                {% render_field form.email class="form-control" placeholder="Email" %}
                <label for="{{ form.email.id_for_label }}">Email</label>
                </div>
            </div>
            </div>

            <div class="row mb-4">
            <div class="col-md-6">
                <div class="form-floating">
                {% render_field form.role class="form-select" %}
                <label for="{{ form.role.id_for_label }}">Role</label>
                </div>
            </div>
            </div>
        </div>
    </div>
    <div class="btn-wrapper mt-5 justify-content-center d-flex">
        <button class="btn btn-primary me-4" type="submit">Add</button>
        <button class="btn btn-secondary" type="reset">Cancel</button>
    </div>
  </form>
  <div class="mt-5">
    <h3 class="my-4">Users</h3>
    <table id="userTable" class="display">
        <thead>
            <tr>
            <th>Sl No.</th>
            <th>Name</th>
            <th>Username</th>
            <th>Email</th>
            <th>Role</th>
            <th>Status</th>
            <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ user.first_name }} {{ user.last_name }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.get_role_display }}</td>
            <td>
                {% if user.is_active %}
                Active
                {% else %}
                Inactive
                {% endif %}
            </td>
            <td>
                <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Actions
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item edit-user" hx-get="{% url 'edit_user' user.id %}" hx-trigger="click" hx-swap="outerHTML" hx-target="#editUserForm" style="cursor: pointer;">✏️ Edit</a></li>
                    <li><a class="dropdown-item dlt-user" href="{% url 'drop_user' user.id %}">🗑️ Drop</a></li>
                </ul>
                </div>
            </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
  </div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModalUser" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Delete User</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this user?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="deleteUserButton">Delete</button>
      </div>
    </div>
  </div>
</div>
<!-- Edit Modal -->
<div class="modal fade" id="editModalUser" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
    	<form id='editUserForm'>
      </form>
    </div>
  </div>
</div>


{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {
      $('#userTable').DataTable();
    });
</script>
{% endblock scripts %}